### ISSUE TITLE
Check for "an"

### ISSUE THREAD

**Issue by clark800** [MauriceButler/jayschema-error-messages#2]
"should be a array" -> "should be an array"

**Comment by MauriceButler** [comment]
Thanks, I assume object is the same too.

I have actually noticed a couple of formatting issues in the last few days that I need to fix up. Ill add this to the list.

**Comment by MauriceButler** [comment]
fixed in commit 3622a71997b1a57c7817b746316fdb304fd6407c

Published in vers 1.0.3
